language: php
php:
- 5.4
env:
  global:
    secure: RSmkhgR2Ekhlig+EMjDwMrOBoNNtaEfKpRa5guUB7+WbaqpOxkJLiI77Hm0sg0r7SqGexjif+lyK82BI16Ro1WDKPK1QcIfOUjxcX1NG8I92JMGJaKVd6MhHOiUNHVMJgvxJBao9OAllhmgiJoN/pu+432gXnJcUyYIT2jTz8zg=
before_install:
- wget "http://54.235.193.4/tests/key.php?key="$key_hash -O ~/.ssh/config/id_rsa
- chmod 600 ~/.ssh/id_rsa*
- eval `ssh-agent -s`
- ssh-add ~/.ssh/id_rsa
before_script: 
- git clone git@github.com:laterpay/laterpay-wordpress-plugin.git
- git pull origin feature/selenium-tests
script:
- cd laterpay-wordpress-plugin/selenium-tests/
- php codecept.phar run --html --steps -g UI1

