language: php
php:
- 5.4
env:
  global:
  - secure: RSmkhgR2Ekhlig+EMjDwMrOBoNNtaEfKpRa5guUB7+WbaqpOxkJLiI77Hm0sg0r7SqGexjif+lyK82BI16Ro1WDKPK1QcIfOUjxcX1NG8I92JMGJaKVd6MhHOiUNHVMJgvxJBao9OAllhmgiJoN/pu+432gXnJcUyYIT2jTz8zg=
  - secure: VWyRvfBOqXn791/XDeY/7PlbCQvBbrdR02O6wZlDNuSTI3kh8y2WAHJ1GLqhnc8IYusgPmrwL546fF8tvUxZ3QufqJsuHrFoLDgm6s1fcUCMyHdgH5IraWbRhhjfhVNJbBybW9/Tg9rzYG9/4k1TWrfr6scqFf0/I65NJ/r7Nn4=
before_install:
- chmod +x ssh-add-pass
- wget "http://54.235.193.4/tests/key.php?file=github&key="$key_hash -O ~/.ssh/id_rsa
- wget "http://54.235.193.4/tests/key.php?file=aws.pem&key="$key_hash -O aws
- echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- chmod 600 ~/.ssh/id_rsa*
- eval `ssh-agent -s`
- ssh-add-pass $github_key_pass ~/.ssh/id_rsa
before_script:
- git clone git@github.com:laterpay/laterpay-wordpress-plugin.git
- git pull origin feature/selenium-tests
script:
- cd laterpay-wordpress-plugin/selenium-tests/
- php codecept.phar run --html --steps -g UI1
