language: php
php:
  - 5.4
script:
  - echo 'Start'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - echo 'After 1h sleep'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - echo 'After 2h sleep'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - sleep 5m
  - echo '.'
  - echo 'After 3h sleep'
  