language: php
php:
  - 5.4
script:
  - php codecept.phar run --html --steps -g dev
  - php codecept.phar run --html --steps -g dev
  - php codecept.phar run --html --steps -g dev
  - php codecept.phar run --html --steps -g dev
  - php codecept.phar run --html --steps -g dev
  - php codecept.phar run --html --steps -g dev
  - php codecept.phar run --html --steps -g dev
  - php codecept.phar run --html --steps -g dev
  - php codecept.phar run --html --steps -g dev
  - php codecept.phar run --html --steps -g dev
  - php codecept.phar run --html --steps -g dev
  - php codecept.phar run --html --steps -g dev
  - php codecept.phar run --html --steps -g dev
  - php codecept.phar run --html --steps -g dev
  - php codecept.phar run --html --steps -g dev
  - php codecept.phar run --html --steps -g dev
  - php codecept.phar run --html --steps -g dev
  - php codecept.phar run --html --steps -g dev
  - php codecept.phar run --html --steps -g dev
  - php codecept.phar run --html --steps -g dev
  - php codecept.phar run --html --steps -g dev
  - php codecept.phar run --html --steps -g dev
  - php codecept.phar run --html --steps -g dev
  - php codecept.phar run --html --steps -g dev
  - php codecept.phar run --html --steps -g dev
  - php codecept.phar run --html --steps -g dev
  - php codecept.phar run --html --steps -g dev
  - php codecept.phar run --html --steps -g dev
  - php codecept.phar run --html --steps -g dev
  - php codecept.phar run --html --steps -g dev
  - php codecept.phar run --html --steps -g dev
  - php codecept.phar run --html --steps -g dev
  - php codecept.phar run --html --steps -g dev
  - php codecept.phar run --html --steps -g dev
  - php codecept.phar run --html --steps -g dev
  - php codecept.phar run --html --steps -g dev
  - php codecept.phar run --html --steps -g dev
  - php codecept.phar run --html --steps -g dev
  - php codecept.phar run --html --steps -g dev
  - php codecept.phar run --html --steps -g dev
  - php codecept.phar run --html --steps -g dev